### ISSUE TITLE
Feature: User can Input Birth Month & Date, returns horoscope

### ISSUE THREAD

**Issue by alexjraymond** [alexjraymond/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Input Birth Month & Date, returns horoscope

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will select a month (January through December) and text input their birth date.  After completing the form, the user will hit the submit button and be taken to the horoscope for their given sign.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CleanShot 2023-01-10 at 09 30 58](https://user-images.githubusercontent.com/117477893/211621506-6c308cc6-950b-4bc3-9d9c-e18ca06dbc00.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create the HTML for the form that creates a birthday entry in the `sign-view="bday-form" element. This form needs to match the format shown in the figma.
- [ ] Complete the HTML form using the appropriate responsive layout classes
- [ ] Make all inputs of the birthday form `required`.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] add a css pseudoclass to indicate the selected month
     - [ ] it should be visibly noticeable to the user as well
- [ ] add an `input` field for the birth date
     - [ ] it should only allow and accept 2 numbers, otherwise it won't submit the form
- [ ] add a `'submit'` event listener to the form that:
     - [ ] prevents the page from refreshing when the form is submitted
     - [ ] updates `sign-view="bday-form"` to match the form input
     - [ ] triggers the API function, which outputs the horoscope for the given `sign-view="bday-form"`
     - [ ] resets the form
     - [ ] hides the form
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
