### ISSUE TITLE
Feature: User can compare with their compatible signs

### ISSUE THREAD

**Issue by alexjraymond** [alexjraymond/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can side-by-side compare their sign with their respective compatible sign

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking the compatible button, the compatible sign's horoscope will appear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![CleanShot 2023-01-10 at 10 18 01](https://user-images.githubusercontent.com/117477893/211631107-afc83fa0-086d-41db-9a1c-9b48408e804e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] make the `compatibility` element clickable
  - [ ] the `eventlistener` for this element will trigger a new `renderHoroscope` DOM tree for the designated sign
  - [ ] the rendered DOM will be appended to the bottom of the page
  - [ ] Remove the `yesterday` & `tomorrow` buttons
  - [ ] stop functionality of the `compatibility` button after one click
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
